apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashuapp
  name: ashuapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashuapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashuapp
    spec:
      imagePullSecrets:
      - name: ashu-reg-cred
      containers:
      - image: tcsindia.azurecr.io/ashuapp:version1
        name: ashuapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
